#services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=fp'
#      - 'POSTGRES_PASSWORD=GFmyjF3eN6d5'
#      - 'POSTGRES_USER=fpadmin'
#    ports:
#      - '5432'
#  zipkin:
#    image: 'openzipkin/zipkin:latest'
#    ports:
#      - '9411'
