apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment-container
          image: localhost:5000/payment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
