apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: flackopay.net
      http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8080
          - path: /api/balances
            pathType: Prefix
            backend:
              service:
                name: balance-service
                port:
                  number: 8080
          - path: /api/outgoing-payments
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8080
          - path: /api/incoming-payments
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8080
          - path: /api/appeals
            pathType: Prefix
            backend:
              service:
                name: appeal-service
                port:
                  number: 8080
          - path: /api/merchants
            pathType: Prefix
            backend:
              service:
                name: merchant-service
                port:
                  number: 8080
          - path: /api/payment-methods
            pathType: Prefix
            backend:
              service:
                name: payment-method-service
                port:
                  number: 8080
          - path: /api/payment-verifications
            pathType: Prefix
            backend:
              service:
                name: payment-verification-service
                port:
                  number: 8080
          - path: /api/terminals
            pathType: Prefix
            backend:
              service:
                name: terminal-service
                port:
                  number: 8080
          - path: /api/trader-teams
            pathType: Prefix
            backend:
              service:
                name: trader-team-service
                port:
                  number: 8080
          - path: /api/payment-verifications/receipts/extract-data
            pathType: Prefix
            backend:
              service:
                name: receipt-data-extractor-service
                port:
                  number: 8080
