apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminal
  template:
    metadata:
      labels:
        app: terminal
    spec:
      containers:
        - name: terminal-container
          image: localhost:5000/terminal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
