apiVersion: v1
kind: Service
metadata:
  name: trader-team-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: trader-team
