apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-verification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-verification
  template:
    metadata:
      labels:
        app: payment-verification
    spec:
      containers:
        - name: payment-verification-container
          image: localhost:5000/payment-verification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
