apiVersion: v1
kind: Service
metadata:
  name: payment-verification-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30087
  selector:
    app: payment-verification
