apiVersion: v1
kind: Service
metadata:
  name: payment-method-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30086
  selector:
    app: payment-method
