apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance
  template:
    metadata:
      labels:
        app: balance
    spec:
      containers:
        - name: balance-container
          image: localhost:5000/balance:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
