apiVersion: v1
kind: Service
metadata:
  name: receipt-data-extractor-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30089
  selector:
    app: receipt-data-extractor
